CREATE TABLE categorias
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR(100) NOT NULL,
    cor        VARCHAR(20)              DEFAULT '#10b981',
    icone      VARCHAR(50),
    usuario_id BIGINT         NOT NULL,
    criado_em  TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_categoria_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);

CREATE TABLE lancamentos
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao    VARCHAR(255)   NOT NULL,
    valor        NUMERIC(15, 2) NOT NULL,
    data         DATE           NOT NULL,
    tipo         VARCHAR(20)    NOT NULL, -- 'RECEITA' ou 'DESPESA'
    pago         BOOLEAN        NOT NULL  DEFAULT FALSE,
    categoria_id BIGINT           NOT NULL,
    usuario_id   BIGINT           NOT NULL,
    criado_em    TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_lancamento_categoria FOREIGN KEY (categoria_id) REFERENCES categorias (id),
    CONSTRAINT fk_lancamento_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);

-- Índices para otimizar filtros por data e usuário
CREATE INDEX idx_lancamentos_usuario_data ON lancamentos (usuario_id, data DESC);
CREATE INDEX idx_categorias_usuario ON categorias (usuario_id);