spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  profiles:
    active:
      -  prod

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:4200}

springdoc:
  api-docs:
    enabled: false