server:
  port: 8080

spring:
  application:
    name: equilibra-backend

  datasource:
    url: jdbc:postgresql://localhost:5434/equilibra
    username: equilibra_user
    password: equilibra_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # SMTP apontando para o container local do Mailpit
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

app:
  mail:
    from: techmichaelmartins@gmail.com
  frontend:
    url: http://localhost:4200
  jwt:
    secret: w7IQvO4P9xd7PXJvZ8TkTCS5uQTLnykyJRDcr6PK0fk=
    expiration-ms: 86400000 # 24 horas