server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: equilibra-api

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5434}/equilibra
    username: ${DATABASE_USER:equilibra_user}
    password: ${DATABASE_PASSWORD:equilibra_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # SMTP apontando para o container local do Mailpit
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  profiles:
    default: dev

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

app:
  mail:
    from: techmichaelmartins@gmail.com
  frontend:
    url: http://localhost:4200
  jwt:
    secret: w7IQvO4P9xd7PXJvZ8TkTCS5uQTLnykyJRDcr6PK0fk=
    expiration-ms: 86400000 # 24 horas